version: '3.3'

services:
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmindb
    ports:
      - "8077:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - UPLOAD_LIMIT=300M
    depends_on:
      - db

  db:
    image: mariadb:10.5.4
    container_name: mariadbbb
    ports:
      - "5506:3306"
    restart: unless-stopped
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
